version: "3.7"
services:
  server:
    build:
      context: "./docker/"
      dockerfile: Dockerfile.server
    container_name: server
    restart: unless-stopped
    volumes:
      - "./server:/server/"
    ports:
      - "28960:28960/udp"
      - "28960:28960"

  admin:
    build:
      context: "./docker/"
      dockerfile: Dockerfile.admin
    container_name: admin
    depends_on:
      - server
    restart: unless-stopped
    volumes:
      - ./server/userraw/logs:/server/logs
      - ./admin:/app
    ports:
      - "1624:1624"

  scp_server:
    image: eeacms/scp-server
    environment:
      DATADIR: /data
      USERID: 1000
      GROUPID: 1000
    ports:
      - "2280:22"
    volumes:
      - ./server:/data